language: php
dist: trusty
os: linux

php:
    - 5.6
    - 7.0
    - nightly

script:
    - vendor/bin/phpunit -c app/ --coverage-clover build/logs/clover.xml

env:
    - SYMFONY__TESTDB=mysql DB=mysql
    - SYMFONY__TESTDB=pgsql DB=pgsql
    - SYMFONY__TESTDB=sqlite DB=sqlite

services:
    - mysql
    - postgresql

jobs:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: nightly
    - php: hhvm

addons:
  code_climate:
    # This should be set up as a secret or so and regenerated as it is already compromized
    # repo_token: 9bf99f3d5903f9f2ae2280f49cc469ef219bb965205cd324847f22d4698257d9

before_script:
  - cp app/config/parameters.php.dist app/config/parameters.php
  - if [[ "$SYMFONY__TESTDB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS partkeepr_test;" -U postgres; fi
  - if [[ "$SYMFONY__TESTDB" == "pgsql" ]]; then psql -c "create database partkeepr_test;" -U postgres; fi
  - if [[ "$SYMFONY__TESTDB" == "mysql" ]]; then mysql -e "DROP database IF EXISTS partkeepr_test;" -uroot; fi
  - if [[ "$SYMFONY__TESTDB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS partkeepr_test;" -uroot; fi
  - composer self-update
  - composer install --prefer-source --no-interaction
  - app/console cache:warmup --env=test
  - app/console doctrine:schema:create --env=test

after_script:
  - vendor/bin/test-reporter
