part_keepr_auth:
    resource: "@PartKeeprAuthBundle/Controller/"
    type:     annotation
    prefix:   /

part_keepr_octopart:
    resource: "@PartKeeprOctoPartBundle/Controller/"
    type:     annotation
    prefix:   /

part_keepr_core:
    resource: "@PartKeeprCoreBundle/Controller/"
    type:     annotation
    prefix:   /

PartKeeprImageBundle:
    resource: "@PartKeeprImageBundle/Controller/"
    type:     annotation
    prefix:   /

PartKeeprProjectBundle:
    resource: "@PartKeeprProjectBundle/Controller/"
    type:     annotation
    prefix:   /

PartKeeprStatisticBundle:
    resource: "@PartKeeprStatisticBundle/Controller/"
    type:     annotation
    prefix:   /

PartKeeprCronloggerBundle:
    resource: "@PartKeeprCronLoggerBundle/Controller/"
    type:     annotation
    prefix:   /

PartKeeprPartBundle:
    resource: "@PartKeeprPartBundle/Controller/"
    type:     annotation
    prefix:   /

PartKeeprMobileFrontendBundle:
    resource: "@PartKeeprMobileFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

_frontend:
    resource: "@PartKeeprFrontendBundle/Resources/config/routing.yml"

_import:
    resource: "@PartKeeprImportBundle/Resources/config/routing.yml"

_export:
    resource: "@PartKeeprExportBundle/Resources/config/routing.yml"

_setup:
    resource: "@PartKeeprSetupBundle/Resources/config/routing.yml"

api:
    resource: "."
    type:     "api"
    prefix:   "/api" # Optional
